{% set version = "1.7.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jobqueue
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jobqueue_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jobqueue/jobqueue_{{ version }}.tar.gz
  sha256: a00e80c037a982903bcaea201390b913ba901b9aa915e75262ce41965c0ebf06

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-cli
    - r-interprocess >=1.2.0
    - r-later
    - r-magrittr
    - r-parallelly
    - r-promises
    - r-ps
    - r-rlang
  run:
    - r-base
    - r-r6
    - r-cli
    - r-interprocess >=1.2.0
    - r-later
    - r-magrittr
    - r-parallelly
    - r-promises
    - r-ps
    - r-rlang

test:
  commands:
    - $R -e "library('jobqueue')"           # [not win]
    - "\"%R%\" -e \"library('jobqueue')\""  # [win]

about:
  home: https://cmmr.github.io/jobqueue/index.html
  dev_url: https://github.com/cmmr/jobqueue
  license: MIT
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
  summary: Takes an R expression and returns a Job object with a $stop() method which can be called to terminate the background job. Also provides timeouts and other mechanisms for automatically terminating a background job. The result of the expression is available synchronously via $result or asynchronously with callbacks
    or through the 'promises' package framework.

extra:
  recipe-maintainers:
    - conda-forge/r
    - dansmith01
